### ISSUE TITLE
Release newer code

### ISSUE THREAD

**Issue by esseti** [django-crispy-forms/crispy-bootstrap4#20]
It's related to this https://github.com/django-crispy-forms/django-crispy-forms/issues/1345  and this commit actually solves it https://github.com/django-crispy-forms/crispy-bootstrap4/blame/main/crispy_bootstrap4/templates/bootstrap4/layout/radioselect.html#L4

but it seems that there's no release that include that code on pypi. Can someone do the release?

**Comment by carltongibson** [comment]
Pip has support for installing straight from GitHub (until the next release is available)

https://pip.pypa.io/en/stable/topics/vcs-support/
