### ISSUE TITLE
Circular dependency problem with django-crispy-forms

### ISSUE THREAD

**Issue by dvzrv** [django-crispy-forms/crispy-bootstrap4#7]
Hi! I'm maintaining django-crispy-forms as a package for Arch Linux.
We're currently doing rebuilds for Python3.11 and I noticed that there is a circular dependency between crispy-bootstrap4 and django-crispy-forms, as both require each other.
This type of dependency is particularly bad for bootstrapping new interpreter versions.

IMHO it would make more sense for django-crispy-forms to require crispy-bootstrap4 and crispy-bootstrap4 to *not* require django-crispy-forms to resolve this issue. The same applies for crispy-bootstrap3 FWIW.

**Comment by dvzrv** [comment]
I believe even the dependency on django should not be there, but only be added for tests.
They are (atomically seen) not runtime dependencies.

**Comment by smithdc1** [comment]
Please could you let me know where you are seeing `django-crispy-forms` depending upon `crispy-bootstrap4`?

As far as I can see, `django-crispy-forms` is only dependant upon `django` itself. 

https://github.com/django-crispy-forms/django-crispy-forms/blob/2f95bdebe6fd611c9a2a7e33e2579086270b98b3/pyproject.toml#L30

**Comment by smithdc1** [comment]
Happy to re-open if the above questions can be answered as currently I don't understand the issue.
